### ISSUE TITLE
Cannot compile for Cauldron

### ISSUE THREAD

**Issue by glixx** [htgoebel/freeplane-mageia#6]
http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/log/freeplane-1.3.11-3.mga5.src.rpm/

**Comment by glixx** [comment]
Fixed in http://svnweb.mageia.org/packages?view=revision&revision=814718

**Comment by htgoebel** [comment]
Thanks. Sorry for not working on this earlier, I'm busy working on other stuff.
